name: Deploy Microservices to Scalingo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2

     - name: Terraform Init
       run: |
         cd scalingo
         terraform init
         terraform apply -auto-approve -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"
       env:
         SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}

  deploy_app:
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Front + API Python
        uses: actions/checkout@v4
        with:
          repository: Arseid/ci-cd-ynov
          path: repo1

      - name: Checkout API Node
        uses: actions/checkout@v4
        with:
          repository: Arseid/ci-cd-ynov-back
          path: repo2

      - name: Créer l'archive
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          mkdir -p app
          
          cp -r repo1 app/front
          rm -rf app/front/server app/front/sqlfiles
          
          cp -r repo1/server app/api-python
          cp -r repo1/sqlfiles app/sqlfiles
          
          cp -r repo2/server app/api-node
          cp -r repo2/mongo-seed app/mongo-seed
          
          cp scalingo/Procfile app/Procfile
          cp scalingo/.buildpacks app/.buildpacks
          echo "3.9" > app/.python-version
          tar -czvf app.tar.gz --exclude='.git' -C app .
          ls -la

      - name: Debug archive contents
        run: |
          mkdir extract && tar -xvzf app.tar.gz -C extract
          echo "::group::Contenu de l'archive"
          find extract
          echo "::endgroup::"          

      - name: Install Scalingo CLI
        uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          region: 'osc-fr1'
          api_token: ${{ secrets.SCALINGO_TOKEN }}

      - name: Déploiement sur Scalingo
        run: scalingo --app ci-cd-ynov-app deploy app.tar.gz
        env:
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
